### ISSUE TITLE
HTML Imports is deprecated

### ISSUE THREAD

**Issue by pierot** [noticeable-app/noticeable-widget#2]
> noticeable-widget.js:1 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

**Comment by lpellegr** [comment]
@pierot Thanks for the report. 

We're working on a new version of the widget along with a new backend and dashboard for the service (that's a huge step!). However, before releasing, we want to have everything aligned and tested. In the meantime, do not worry, even if HTML imports are deprecated and removed, a light polyfill will be automatically loaded to make the current widget work smoothly until the new version is available.

**Comment by lpellegr** [comment]
A new widget and SDK have been deployed. HTML imports are no longer used.
